### PR TITLE
Fix installation of pip with setuptools and wheel dependencies for Python < 3.13

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/conda-forge/pip-feedstock/issues/132 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
> Hi! This is the friendly automated conda-forge-linting service.
> 
> I just wanted to let you know that I linted all conda-recipes in your PR (`recipe/meta.yaml`) and found it was in an excellent condition.
> 
> I do have some suggestions for making it better though...
> 
> For **recipe/meta.yaml**:
> 
>     * ℹ️ `noarch: python` recipes should usually follow the syntax in our [documentation](https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python) for specifying the Python version.
>       
>       * For the `host` section of the recipe, you should usually use `python {{ python_min }}` for the `python` entry.
>       * If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).
> 
> 
> This message was generated by GitHub Actions workflow run https://github.com/conda-forge/conda-forge-webservices/actions/runs/12369226145. Examine the logs at this URL for more detail.

Given the current structure of the recipe, we can't follow the structure used by other python noarch packages.

**Review by h-vetinari — APPROVED** [review]
Thanks @traversaro!

**Comment by h-vetinari** [comment]
Merging this due to breakage observed and #131 having been obviously incorrect.

**Pull request merged**
