### PR TITLE
Release 9.0.0

### PR DESCRIPTION
**Pull request by jakirkham**
```
**9.0.0 (2016-11-02)**

* **BACKWARD INCOMPATIBLE** Remove the attempted autodetection of requirement
  names from URLs, URLs must include a name via ``#egg=``.

* **DEPRECATION** ``pip install --egg`` have been deprecated and will be
  removed in the future. This "feature" has a long list of drawbacks which 
  break nearly all of pip's other features in subtle and hard-to-diagnose
  ways.

* **DEPRECATION** ``--default-vcs`` option (:issue:`4052`).

* **WARNING** pip 9 cache can break forward compatibility with previous pip
  versions if your package repository allows chunked responses (:issue:`4078`).

* Add a ``pip check`` command to check installed packages dependencies
  (:pull:`3750`).

* Add option allowing user to abort pip operation if file/directory exists

* Add Appveyor CI

* Uninstall existing packages when performing an editable installation of
  the same packages (:issue:`1548`).

* ``pip show`` is less verbose by default. ``--verbose`` prints multiline fields.
  (:pull:`3858`).

* Add optional column formatting to ``pip list`` (:issue:`3651`).

* Add ``--not-required`` option to ``pip list``, which lists packages that are
  not dependencies of other packages.

* Fix builds on systems with symlinked ``/tmp`` directory for custom
  builds such as numpy (:pull:`3701`).

* Fix regression in ``pip freeze``: when there is more than one git remote,
  priority is given to the remote named ``origin`` (:pull:`3708`, :issue:`3616`).

* Fix crash when calling ``pip freeze`` with invalid requirement installed
  (:pull:`3704`, :issue:`3681`).

* Allow multiple ``--requirement`` files in ``pip freeze`` (:pull:`3703`).

* Implementation of pep-503 ``data-requires-python``. When this field is
  present for a release link, pip will ignore the download when
  installing to a Python version that doesn't satisfy the requirement.

* ``pip wheel`` now works on editable packages too (it was only working on
  editable dependencies before); this allows running ``pip wheel`` on the result
  of ``pip freeze`` in presence of editable requirements (:pull:`3695`,
  :issue:`3291`).

* Load credentials from ``.netrc`` files (:pull:`3715`, :issue:`3569`).

* Add ``--platform``, ``--python-version``, ``--implementation`` and ``--abi`` parameters to
  ``pip download``. These allow utilities and advanced users to gather
  distributions for interpreters other than the one pip is being run on.
  (:pull:`3760`)

* Skip scanning virtual environments, even when venv/bin/python is a dangling
  symlink.

* Added ``pip completion`` support for the ``fish`` shell.

* Fix problems on Windows on Python 2 when username or hostname contains
  non-ASCII characters (:issue:`3463`, :pull:`3970`, :pull:`4000`).

* Use ``git fetch --tags`` to fetch tags in addition to everything else that
  is normally fetched; this is necessary in case a git requirement url
  points to a tag or commit that is not on a branch (:pull:`3791`)

* Normalize package names before using in ``pip show`` (:issue:`3976`)

* Raise when Requires-Python do not match the running version and add
  ``--ignore-requires-python`` option as escape hatch (:pull:`3846`).

* Report the correct installed version when performing an upgrade in some
  corner cases (:issue:`2382`)

* Add ``-i`` shorthand for ``--index`` flag in ``pip search``

* Do not optionally load C dependencies in requests (:issue:`1840`,
  :issue:`2930`, :issue:`3024`)

* Strip authentication from SVN url prior to passing it to ``svn``
  (:pull:`3697`, :issue:`3209`).

* Also install in platlib with ``--target`` option (:pull:`3694`, :issue:`3682`).

* Restore the ability to use inline comments in requirements files passed to
``pip freeze`` (:issue:`3680`).
```

cc @conda-forge/core

### CODE REVIEW

**Comment by jakirkham** [comment]
Please merge when you are comfortable @conda-forge/core .

**Comment by scopatz** [comment]
Looks like appveyor is failing

**Comment by jakirkham** [comment]
It's not related to the package though. Instead it is issue ( https://github.com/conda-forge/conda-smithy/issues/351 ). We aren't sure why it is occurring. PR ( https://github.com/conda-forge/conda-smithy/issues/370 ) seems to solve the issue. Unfortunately we still lack a good idea of why. Will restart AppVeyor here and hope it doesn't run into this spurious issue again.

xref: https://ci.appveyor.com/project/conda-forge/pip-feedstock/build/1.0.6/job/vp1nnsu8yk24kvmv

**Comment by michaelaye** [comment]
Note also that 9.0.1 is out since Nov 6 (yesterday).

**Comment by jakirkham** [comment]
Yep saw that yesterday. Will happily issue a version bump after this is merged.

FYI CI is now passing @scopatz . 😉

**Comment by mwcraig** [comment]
About to merge, but thought I'd ask a protocol question since this came up in another repo too: is it ok for members of core to merge feedstock PRs on which they are not maintainers?

**Comment by jakirkham** [comment]
When it has come to re-rendering PRs, the answer has normally been yes. In some cases, core members have merged PRs that seemed sound if a maintainer was incredibly slow to respond. For this particular case, all the maintainers here are core members (though not vice versa).

In general, version bumps have been ok for self-merges. That being said, this PR was a major version change in `pip`. So wanted to make sure we were ok with those changes. FWIW I don't think any of the breaking changes impact our work at conda-forge. They seem to be centered on end users working with advanced features in `pip`.

**Comment by jakirkham** [comment]
Prepping for `9.0.1` in PR ( https://github.com/conda-forge/pip-feedstock/pull/4 ).

**Pull request merged**
